# pass -edg:w to turn off front-end warnings
# pass -c so ROSE doesn't give us spurious output

echo "Testing TestCases/AliasTests/alias1.c\n\tTestResults/FIAlias/alias1.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/alias1.c
echo "Testing TestCases/AliasTests/alias2.c\n\tTestResults/FIAlias/alias2.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/alias2.c
echo "Testing TestCases/AliasTests/alias3.c\n\tTestResults/FIAlias/alias3.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/alias3.c
echo "Testing TestCases/AliasTests/alias4.c\n\tTestResults/FIAlias/alias4.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/alias4.c
echo "Testing TestCases/AliasTests/alias4b.c\n\tTestResults/FIAlias/alias4b.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/alias4b.c
echo "Testing TestCases/AliasTests/funCall.c\n\tTestResults/FIAlias/funCall.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/funCall.c
echo "Testing TestCases/AliasTests/utke.c\n\tTestResults/FIAlias/utke.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/utke.c
echo "Testing TestCases/AliasTests/OAWikiEx.c\n\tTestResults/AliasTests/OAWikiEx.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/OAWikiEx.c
echo "Testing TestCases/AliasTests/comma.c\n\tTestResults/AliasTests/comma.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/comma.c
echo "Testing TestCases/AliasTests/constQualified.c\n\tTestResults/AliasTests/constQualified.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/constQualified.c

# C++ tests
echo "Testing TestCases/AliasTests/HindEtAlIBM95Fig4.C\n\tTestResults/AliasTests/HindEtAlIBM95Fig4.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/HindEtAlIBM95Fig4.C
echo "Testing TestCases/AliasTests/HindEtAlISSTA00Fig1.C\n\tTestResults/AliasTests/HindEtAlISSTA00Fig1.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/HindEtAlISSTA00Fig1.C
echo "Testing TestCases/AliasTests/LattnerEtAl03Fig1.C\n\tTestResults/AliasTests/LattnerEtAl03Fig1.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/LattnerEtAl03Fig1.C
echo "Testing TestCases/AliasTests/PandeEtAlRutgers05.C\n\tTestResults/AliasTests/PandeEtAlRutgers05.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/PandeEtAlRutgers05.C
echo "Testing TestCases/AliasTests/PioliThesis99Fig1.C\n\tTestResults/AliasTests/PioliThesis99Fig1.C checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/PioliThesis99Fig1.C
echo "Testing TestCases/AliasTests/PioliThesis99Fig3.C\n\tTestResults/AliasTests/PioliThesis99Fig3.C checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/PioliThesis99Fig3.C
echo "Testing TestCases/AliasTests/ref.C\n\tTestResults/AliasTests/ref.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/ref.C
echo "Testing TestCases/AliasTests/refCall.C\n\tTestResults/AliasTests/refCall.C checked by BSW"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/refCall.C
echo "Testing TestCases/AliasTests/refClass.C\n\tTestResults/AliasTests/refClass.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/refClass.C
echo "Testing TestCases/AliasTests/refParam.C\n\tTestResults/AliasTests/refParam.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/refParam.C
echo "Testing TestCases/AliasTests/RinardEtAlPLDI96Fig4.C\n\tTestResults/AliasTests/RinardEtAlPLDI96Fig4.C checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RinardEtAlPLDI96Fig4.C

# C tests
echo "Testing TestCases/AliasTests/diffArrays.c\n\tTestResults/AliasTests/diffArrays.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/diffArrays.c
echo "Testing TestCases/AliasTests/diffTypes.c\n\tTestResults/AliasTests/diffTypes.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/diffTypes.c
echo "Testing TestCases/AliasTests/LiangEtAl00.c\n\tTestResults/AliasTests/LiangEtAl00.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/LiangEtAl00.c
echo "Testing TestCases/AliasTests/LiangEtAl99.c\n\tTestResults/AliasTests/LiangEtAl99.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/LiangEtAl99.c
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig2.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig2.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/LiangEtAlICSM99Fig2.c
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig5.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig5.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/LiangEtAlICSM99Fig5.c
echo "Testing TestCases/AliasTests/RyderEtAlFig11.c\n\tTestResults/AliasTests/RyderEtAlFig11.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig11.c
echo "Testing TestCases/AliasTests/RyderEtAlFig14.c\n\tTestResults/AliasTests/RyderEtAlFig14.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig14.c
echo "Testing TestCases/AliasTests/RyderEtAlFig15.c\n\tTestResults/AliasTests/RyderEtAlFig15.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig15.c
echo "Testing TestCases/AliasTests/RyderEtAlFig1a.c\n\tTestResults/AliasTests/RyderEtAlFig1a.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig1a.c
echo "Testing TestCases/AliasTests/RyderEtAlFig1b.c\n\tTestResults/AliasTests/RyderEtAlFig1b.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig1b.c
echo "Testing TestCases/AliasTests/RyderEtAlFig1c.c\n\tTestResults/AliasTests/RyderEtAlFig1c.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig1c.c
echo "Testing TestCases/AliasTests/RyderEtAlFig2.c\n\tTestResults/AliasTests/RyderEtAlFig2.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig2.c
echo "Testing TestCases/AliasTests/RyderEtAlFig3.c\n\tTestResults/AliasTests/RyderEtAlFig3.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig3.c
echo "Testing TestCases/AliasTests/RyderEtAlFig7.c\n\tTestResults/AliasTests/RyderEtAlFig7.c checked by MMS"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig7.c
echo "Testing TestCases/AliasTests/RyderEtAlFig9.c\n\tTestResults/AliasTests/RyderEtAlFig9.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/RyderEtAlFig9.c
echo "Testing TestCases/AliasTests/YongEtAlPLDI99.c\n\tTestResults/AliasTests/YongEtAlPLDI99.c checked by ???"
./OATest -edg:w --oa-FIAlias -c TestCases/AliasTests/YongEtAlPLDI99.c

