# pass -edg:w to turn off front-end warnings
# pass -c so ROSE doesn't give us spurious output

echo "Testing TestCases/AliasTests/alias1.c\n\tTestResults/FIAliasAliasMap/alias1.c checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias1.c > t
diff t TestResults/FIAliasAliasMap/alias1.c.out
echo "Testing TestCases/AliasTests/alias2.c\n\tTestResults/FIAliasAliasMap/alias2.c checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias2.c > t
diff t TestResults/FIAliasAliasMap/alias2.c.out
echo "Testing TestCases/AliasTests/alias3.c\n\tTestResults/FIAliasAliasMap/alias3.c checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias3.c > t
diff t TestResults/FIAliasAliasMap/alias3.c.out
echo "Testing TestCases/AliasTests/alias4.c\n\tTestResults/FIAliasAliasMap/alias4.c checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias4.c > t
diff t TestResults/FIAliasAliasMap/alias4.c.out
echo "Testing TestCases/AliasTests/alias4b.c\n\tTestResults/FIAliasAliasMap/alias4b.c checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias4b.c > t
diff t TestResults/FIAliasAliasMap/alias4b.c.out
echo "Testing TestCases/AliasTests/funCall.c\n\tTestResults/FIAliasAliasMap/funCall.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/funCall.c > t
diff t TestResults/FIAliasAliasMap/funCall.c.out
echo "Testing TestCases/AliasTests/utke.c\n\tTestResults/FIAliasAliasMap/utke.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/utke.c > t
diff t TestResults/FIAliasAliasMap/utke.c.out
echo "Testing TestCases/AliasTests/OAWikiEx.c\n\tTestResults/AliasTests/OAWikiEx.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/OAWikiEx.c > t
diff t TestResults/FIAliasAliasMap/OAWikiEx.c.out
echo "Testing TestCases/AliasTests/comma.c\n\tTestResults/AliasTests/comma.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/comma.c > t
diff t TestResults/FIAliasAliasMap/comma.c.out
echo "Testing TestCases/AliasTests/constQualified.c\n\tTestResults/AliasTests/constQualified.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/constQualified.c > t
diff t TestResults/FIAliasAliasMap/constQualified.c.out

# C++ tests
echo "Testing TestCases/AliasTests/HindEtAlIBM95Fig4.C\n\tTestResults/AliasTests/HindEtAlIBM95Fig4.C checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/HindEtAlIBM95Fig4.C > t
diff t TestResults/FIAliasAliasMap/HindEtAlIBM95Fig4.C.out
echo "Testing TestCases/AliasTests/HindEtAlISSTA00Fig1.C\n\tTestResults/AliasTests/HindEtAlISSTA00Fig1.C checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/HindEtAlISSTA00Fig1.C > t
diff t TestResults/FIAliasAliasMap/HindEtAlISSTA00Fig1.C.out
echo "Testing TestCases/AliasTests/LattnerEtAl03Fig1.C\n\tTestResults/AliasTests/LattnerEtAl03Fig1.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/LattnerEtAl03Fig1.C > t
diff t TestResults/FIAliasAliasMap/LattnerEtAl03Fig1.C.out
echo "Testing TestCases/AliasTests/PandeEtAlRutgers05.C\n\tTestResults/AliasTests/PandeEtAlRutgers05.C checked by BW"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/PandeEtAlRutgers05.C > t
diff t TestResults/FIAliasAliasMap/PandeEtAlRutgers05.C.out
echo "Testing TestCases/AliasTests/PioliThesis99Fig1.C\n\tTestResults/AliasTests/PioliThesis99Fig1.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/PioliThesis99Fig1.C > t
diff t TestResults/FIAliasAliasMap/PioliThesis99Fig1.C.out
echo "Testing TestCases/AliasTests/PioliThesis99Fig3.C\n\tTestResults/AliasTests/PioliThesis99Fig3.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/PioliThesis99Fig3.C > t
diff t TestResults/FIAliasAliasMap/PioliThesis99Fig3.C.out
echo "Testing TestCases/AliasTests/ref.C\n\tTestResults/AliasTests/ref.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/ref.C > t
diff t TestResults/FIAliasAliasMap/ref.C.out
echo "Testing TestCases/AliasTests/refCall.C\n\tTestResults/AliasTests/refCall.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/refCall.C > t
diff t TestResults/FIAliasAliasMap/refCall.C.out
echo "Testing TestCases/AliasTests/refClass.C\n\tTestResults/AliasTests/refClass.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/refClass.C > t
diff t TestResults/FIAliasAliasMap/refClass.C.out
echo "Testing TestCases/AliasTests/refParam.C\n\tTestResults/AliasTests/refParam.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/refParam.C > t
diff t TestResults/FIAliasAliasMap/refParam.C.out
echo "Testing TestCases/AliasTests/RinardEtAlPLDI96Fig4.C\n\tTestResults/AliasTests/RinardEtAlPLDI96Fig4.C checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RinardEtAlPLDI96Fig4.C > t
diff t TestResults/FIAliasAliasMap/RinardEtAlPLDI96Fig4.C.out

# C tests
echo "Testing TestCases/AliasTests/diffArrays.c\n\tTestResults/AliasTests/diffArrays.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/diffArrays.c > t
diff t TestResults/FIAliasAliasMap/diffArrays.c.out
echo "Testing TestCases/AliasTests/diffTypes.c\n\tTestResults/AliasTests/diffTypes.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/diffTypes.c > t
diff t TestResults/FIAliasAliasMap/diffTypes.c.out
echo "Testing TestCases/AliasTests/LiangEtAl00.c\n\tTestResults/AliasTests/LiangEtAl00.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/LiangEtAl00.c > t
diff t TestResults/FIAliasAliasMap/LiangEtAl00.c.out
echo "Testing TestCases/AliasTests/LiangEtAl99.c\n\tTestResults/AliasTests/LiangEtAl99.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/LiangEtAl99.c > t
diff t TestResults/FIAliasAliasMap/LiangEtAl99.c.out
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig2.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig2.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/LiangEtAlICSM99Fig2.c > t
diff t TestResults/FIAliasAliasMap/LiangEtAlICSM99Fig2.c.out
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig5.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig5.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/LiangEtAlICSM99Fig5.c > t
diff t TestResults/FIAliasAliasMap/LiangEtAlICSM99Fig5.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig11.c\n\tTestResults/AliasTests/RyderEtAlFig11.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig11.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig11.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig14.c\n\tTestResults/AliasTests/RyderEtAlFig14.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig14.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig14.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig15.c\n\tTestResults/AliasTests/RyderEtAlFig15.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig15.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig15.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1a.c\n\tTestResults/AliasTests/RyderEtAlFig1a.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig1a.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig1a.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1b.c\n\tTestResults/AliasTests/RyderEtAlFig1b.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig1b.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig1b.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1c.c\n\tTestResults/AliasTests/RyderEtAlFig1c.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig1c.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig1c.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig2.c\n\tTestResults/AliasTests/RyderEtAlFig2.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig2.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig2.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig3.c\n\tTestResults/AliasTests/RyderEtAlFig3.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig3.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig3.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig7.c\n\tTestResults/AliasTests/RyderEtAlFig7.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig7.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig7.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig9.c\n\tTestResults/AliasTests/RyderEtAlFig9.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/RyderEtAlFig9.c > t
diff t TestResults/FIAliasAliasMap/RyderEtAlFig9.c.out
echo "Testing TestCases/AliasTests/YongEtAlPLDI99.c\n\tTestResults/AliasTests/YongEtAlPLDI99.c checked by ???"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/YongEtAlPLDI99.c > t
diff t TestResults/FIAliasAliasMap/YongEtAlPLDI99.c.out

rm t
