# pass -edg:w to turn off front-end warnings
# pass -c so ROSE doesn't give us spurious output

echo "Testing ./TestCases/CFGtests/Beata-040819.c\n\tTestResults/UnreleasedCFG/Beata-040819.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/Beata-040819.c > t
diff t TestResults/UnreleasedCFG/Beata-040819.c.out
echo "Testing ./TestCases/CFGtests/dowhile.c\n\tTestResults/UnreleasedCFG/dowhile.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/dowhile.c > t
diff t TestResults/UnreleasedCFG/dowhile.c.out
echo "Testing ./TestCases/CFGtests/for.c\n\tTestResults/UnreleasedCFG/for.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/for.c > t
diff t TestResults/UnreleasedCFG/for.c.out
echo "Testing ./TestCases/CFGtests/forNest2.c\n\tTestResults/UnreleasedCFG/forNest2.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/forNest2.c > t
diff t TestResults/UnreleasedCFG/forNest2.c.out
echo "Testing ./TestCases/CFGtests/switch10.c\n\tTestResults/UnreleasedCFG/switch10.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch10.c > t
diff t TestResults/UnreleasedCFG/switch10.c.out
echo "Testing ./TestCases/CFGtests/switch11.c\n\tTestResults/UnreleasedCFG/switch11.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch11.c > t
diff t TestResults/UnreleasedCFG/switch11.c.out
echo "Testing ./TestCases/CFGtests/switch12.c\n\tTestResults/UnreleasedCFG/switch12.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch12.c > t
diff t TestResults/UnreleasedCFG/switch12.c.out
echo "Testing ./TestCases/CFGtests/switch1.c\n\tTestResults/UnreleasedCFG/switch1.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch1.c > t
diff t TestResults/UnreleasedCFG/switch1.c.out
echo "Testing ./TestCases/CFGtests/switch2.c\n\tTestResults/UnreleasedCFG/switch2.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch2.c > t
diff t TestResults/UnreleasedCFG/switch2.c.out
echo "Testing ./TestCases/CFGtests/switch3.c\n\tTestResults/UnreleasedCFG/switch3.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch3.c > t
diff t TestResults/UnreleasedCFG/switch3.c.out
echo "Testing ./TestCases/CFGtests/switch4.c\n\tTestResults/UnreleasedCFG/switch4.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch4.c > t
diff t TestResults/UnreleasedCFG/switch4.c.out
echo "Testing ./TestCases/CFGtests/switch5.c\n\tTestResults/UnreleasedCFG/switch5.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch5.c > t
diff t TestResults/UnreleasedCFG/switch5.c.out
echo "Testing ./TestCases/CFGtests/switch6.c\n\tTestResults/UnreleasedCFG/switch6.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch6.c > t
diff t TestResults/UnreleasedCFG/switch6.c.out
echo "Testing ./TestCases/CFGtests/switch7.c\n\tTestResults/UnreleasedCFG/switch7.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch7.c > t
diff t TestResults/UnreleasedCFG/switch7.c.out
echo "Testing ./TestCases/CFGtests/switch8.c\n\tTestResults/UnreleasedCFG/switch8.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch8.c > t
diff t TestResults/UnreleasedCFG/switch8.c.out
echo "Testing ./TestCases/CFGtests/switch9.c\n\tTestResults/UnreleasedCFG/switch9.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/switch9.c > t
diff t TestResults/UnreleasedCFG/switch9.c.out
echo "Testing ./TestCases/CFGtests/while.c\n\tTestResults/UnreleasedCFG/while.c checked by ???"
./OATest -edg:w --oa-CFG -c ./TestCases/CFGtests/while.c > t
diff t TestResults/UnreleasedCFG/while.c.out

rm t
