./testAll.exe --oa-MemRefExpr TestProgs/t1.c > TestResults/MemRefExpr/t1.c.out
./testAll.exe --oa-MemRefExpr TestProgs/t2.c > TestResults/MemRefExpr/t2.c.out
./testAll.exe --oa-MemRefExpr TestProgs/t3.c > TestResults/MemRefExpr/t3.c.out
./testAll.exe --oa-MemRefExpr TestProgs/t4.c > TestResults/MemRefExpr/t4.c.out
./testAll.exe --oa-MemRefExpr TestProgs/t5.c > TestResults/MemRefExpr/t5.c.out
./testAll.exe --oa-MemRefExpr TestProgs/MemRefExprTestInput.C > TestResults/MemRefExpr/MemRefExprTestInput.C.out
