# comment in file.test
# Regression tests for Reaching Definitio 
testname::CFG
inputdir::TestCases/CFGtests
outputdir::TestResults/CFGtests
driverexec::./OATest -edg:w --oa-CFG -c

# list of tests
#       input file,     status
test::  for.c,          Checked by PLM 05/12/08
test::  while.c,        Checked by PLM 05/12/08
test::  dowhile.c,      Checked by PLM 05/12/08
test::  switch1.c,      Checked by PLM 05/12/08


