# pass -edg:w to turn off front-end warnings
# pass -c so ROSE doesn't give us spurious output

echo "Testing TestCases/AliasTests/alias1.c\n\tTestResults/UnreleasedFIAlias/alias1.c checked by MMS"
cat TestResults/UnreleasedFIAlias/alias1.c.out
echo "Testing TestCases/AliasTests/alias2.c\n\tTestResults/UnreleasedFIAlias/alias2.c checked by MMS"
cat TestResults/UnreleasedFIAlias/alias2.c.out
echo "Testing TestCases/AliasTests/alias3.c\n\tTestResults/UnreleasedFIAlias/alias3.c checked by MMS"
cat TestResults/UnreleasedFIAlias/alias3.c.out
echo "Testing TestCases/AliasTests/alias4.c\n\tTestResults/UnreleasedFIAlias/alias4.c checked by MMS"
cat TestResults/UnreleasedFIAlias/alias4.c.out
echo "Testing TestCases/AliasTests/alias4b.c\n\tTestResults/UnreleasedFIAlias/alias4b.c checked by MMS"
cat TestResults/UnreleasedFIAlias/alias4b.c.out
echo "Testing TestCases/AliasTests/funCall.c\n\tTestResults/UnreleasedFIAlias/funCall.c checked by MMS"
cat TestResults/UnreleasedFIAlias/funCall.c.out
echo "Testing TestCases/AliasTests/utke.c\n\tTestResults/UnreleasedFIAlias/utke.c checked by MMS"
cat TestResults/UnreleasedFIAlias/utke.c.out
echo "Testing TestCases/AliasTests/OAWikiEx.c\n\tTestResults/AliasTests/OAWikiEx.c checked by MMS"
cat TestResults/UnreleasedFIAlias/OAWikiEx.c.out
echo "Testing TestCases/AliasTests/comma.c\n\tTestResults/AliasTests/comma.c checked by MMS"
cat TestResults/UnreleasedFIAlias/comma.c.out
echo "Testing TestCases/AliasTests/constQualified.c\n\tTestResults/AliasTests/constQualified.c checked by MMS"
cat TestResults/UnreleasedFIAlias/constQualified.c.out

# C++ tests
echo "Testing TestCases/AliasTests/HindEtAlIBM95Fig4.C\n\tTestResults/AliasTests/HindEtAlIBM95Fig4.C checked by ???"
cat TestResults/UnreleasedFIAlias/HindEtAlIBM95Fig4.C.out
echo "Testing TestCases/AliasTests/HindEtAlISSTA00Fig1.C\n\tTestResults/AliasTests/HindEtAlISSTA00Fig1.C checked by ???"
cat TestResults/UnreleasedFIAlias/HindEtAlISSTA00Fig1.C.out
echo "Testing TestCases/AliasTests/LattnerEtAl03Fig1.C\n\tTestResults/AliasTests/LattnerEtAl03Fig1.C checked by ???"
cat TestResults/UnreleasedFIAlias/LattnerEtAl03Fig1.C.out
echo "Testing TestCases/AliasTests/PandeEtAlRutgers05.C\n\tTestResults/AliasTests/PandeEtAlRutgers05.C checked by ???"
cat TestResults/UnreleasedFIAlias/PandeEtAlRutgers05.C.out
echo "Testing TestCases/AliasTests/PioliThesis99Fig1.C\n\tTestResults/AliasTests/PioliThesis99Fig1.C checked by MMS"
cat TestResults/UnreleasedFIAlias/PioliThesis99Fig1.C.out
echo "Testing TestCases/AliasTests/PioliThesis99Fig3.C\n\tTestResults/AliasTests/PioliThesis99Fig3.C checked by MMS"
cat TestResults/UnreleasedFIAlias/PioliThesis99Fig3.C.out
echo "Testing TestCases/AliasTests/ref.C\n\tTestResults/AliasTests/ref.C checked by BSW"
cat TestResults/UnreleasedFIAlias/ref.C.out
echo "Testing TestCases/AliasTests/refCall.C\n\tTestResults/AliasTests/refCall.C checked by BSW"
cat TestResults/UnreleasedFIAlias/refCall.C.out
echo "Testing TestCases/AliasTests/refClass.C\n\tTestResults/AliasTests/refClass.C checked by BSW"
cat TestResults/UnreleasedFIAlias/refClass.C.out
echo "Testing TestCases/AliasTests/refParam.C\n\tTestResults/AliasTests/refParam.C checked by BSW"
cat TestResults/UnreleasedFIAlias/refParam.C.out
echo "Testing TestCases/AliasTests/RinardEtAlPLDI96Fig4.C\n\tTestResults/AliasTests/RinardEtAlPLDI96Fig4.C checked by ???"
cat TestResults/UnreleasedFIAlias/RinardEtAlPLDI96Fig4.C.out

# C tests
echo "Testing TestCases/AliasTests/diffArrays.c\n\tTestResults/AliasTests/diffArrays.c checked by BSW"
cat TestResults/UnreleasedFIAlias/diffArrays.c.out
echo "Testing TestCases/AliasTests/diffTypes.c\n\tTestResults/AliasTests/diffTypes.c checked by MMS"
cat TestResults/UnreleasedFIAlias/diffTypes.c.out
echo "Testing TestCases/AliasTests/LiangEtAl00.c\n\tTestResults/AliasTests/LiangEtAl00.c checked by MMS"
cat TestResults/UnreleasedFIAlias/LiangEtAl00.c.out
echo "Testing TestCases/AliasTests/LiangEtAl99.c\n\tTestResults/AliasTests/LiangEtAl99.c checked by MMS"
cat TestResults/UnreleasedFIAlias/LiangEtAl99.c.out
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig2.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig2.c checked by MMS"
cat TestResults/UnreleasedFIAlias/LiangEtAlICSM99Fig2.c.out
echo "Testing TestCases/AliasTests/LiangEtAlICSM99Fig5.c\n\tTestResults/AliasTests/LiangEtAlICSM99Fig5.c checked by MMS"
cat TestResults/UnreleasedFIAlias/LiangEtAlICSM99Fig5.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig11.c\n\tTestResults/AliasTests/RyderEtAlFig11.c checked by MMS"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig11.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig14.c\n\tTestResults/AliasTests/RyderEtAlFig14.c checked by MMS"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig14.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig15.c\n\tTestResults/AliasTests/RyderEtAlFig15.c checked by BW"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig15.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1a.c\n\tTestResults/AliasTests/RyderEtAlFig1a.c checked by MMS"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig1a.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1b.c\n\tTestResults/AliasTests/RyderEtAlFig1b.c checked by BW"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig1b.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig1c.c\n\tTestResults/AliasTests/RyderEtAlFig1c.c checked by BW"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig1c.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig2.c\n\tTestResults/AliasTests/RyderEtAlFig2.c checked by BW"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig2.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig3.c\n\tTestResults/AliasTests/RyderEtAlFig3.c checked by MMS"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig3.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig7.c\n\tTestResults/AliasTests/RyderEtAlFig7.c checked by MMS"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig7.c.out
echo "Testing TestCases/AliasTests/RyderEtAlFig9.c\n\tTestResults/AliasTests/RyderEtAlFig9.c checked by BW"
cat TestResults/UnreleasedFIAlias/RyderEtAlFig9.c.out
echo "Testing TestCases/AliasTests/YongEtAlPLDI99.c\n\tTestResults/AliasTests/YongEtAlPLDI99.c checked by BW"
cat TestResults/UnreleasedFIAlias/YongEtAlPLDI99.c.out

