# pass -edg:w to turn off front-end warnings
# pass -c so ROSE doesn't give us spurious output

echo "Testing TestCases/MemRefExprTests/t1.c\n\tTestResults/UnreleasedMemRefExprTests/t1.c checked by BW"
cat TestResults/UnreleasedMemRefExpr/t1.c.out
echo "Testing TestCases/MemRefExprTests/t2.c\n\tTestResults/UnreleasedMemRefExprTests/t2.c checked by BW"
cat TestResults/UnreleasedMemRefExpr/t2.c.out
echo "Testing TestCases/MemRefExprTests/t3.c\n\tTestResults/UnreleasedMemRefExprTests/t3.c checked by BW"
cat TestResults/UnreleasedMemRefExpr/t3.c.out
echo "Testing TestCases/MemRefExprTests/t4.c\n\tTestResults/UnreleasedMemRefExprTests/t4.c checked by BW"
cat TestResults/UnreleasedMemRefExpr/t4.c.out
echo "Testing TestCases/MemRefExprTests/t5.c\n\tTestResults/UnreleasedMemRefExprTests/t5.c checked by BW"
cat TestResults/UnreleasedMemRefExpr/t5.c.out
echo "Testing TestCases/MemRefExprTests/MemRefExprTestInput.C\n\tTestResults/UnreleasedMemRefExprTests/MemRefExprTestInput.C checked by BW"
cat TestResults/UnreleasedMemRefExpr/MemRefExprTestInput.C.out

