echo "Generating TestResults/FIAliasAliasTag/addressOf.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/addressOf.c >& TestResults/FIAliasAliasTag/addressOf.c.out
echo "Generating TestResults/FIAliasAliasTag/aggregateInit.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/aggregateInit.c >& TestResults/FIAliasAliasTag/aggregateInit.c.out
echo "Generating TestResults/FIAliasAliasTag/alias1.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias1.c >& TestResults/FIAliasAliasTag/alias1.c.out
echo "Generating TestResults/FIAliasAliasTag/alias2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias2.c >& TestResults/FIAliasAliasTag/alias2.c.out
echo "Generating TestResults/FIAliasAliasTag/alias3.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias3.c >& TestResults/FIAliasAliasTag/alias3.c.out
echo "Generating TestResults/FIAliasAliasTag/alias4b.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias4b.c >& TestResults/FIAliasAliasTag/alias4b.c.out
echo "Generating TestResults/FIAliasAliasTag/alias4.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias4.c >& TestResults/FIAliasAliasTag/alias4.c.out
echo "Generating TestResults/FIAliasAliasTag/assignOps.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/assignOps.c >& TestResults/FIAliasAliasTag/assignOps.c.out
echo "Generating TestResults/FIAliasAliasTag/assignReturn.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/assignReturn.c >& TestResults/FIAliasAliasTag/assignReturn.c.out
echo "Generating TestResults/FIAliasAliasTag/comma.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/comma.c >& TestResults/FIAliasAliasTag/comma.c.out
echo "Generating TestResults/FIAliasAliasTag/constQualified.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/constQualified.c >& TestResults/FIAliasAliasTag/constQualified.c.out
echo "Generating TestResults/FIAliasAliasTag/diffArrays.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/diffArrays.c >& TestResults/FIAliasAliasTag/diffArrays.c.out
echo "Generating TestResults/FIAliasAliasTag/diffTypes.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/diffTypes.c >& TestResults/FIAliasAliasTag/diffTypes.c.out
echo "Generating TestResults/FIAliasAliasTag/fields2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/fields2.c >& TestResults/FIAliasAliasTag/fields2.c.out
echo "Generating TestResults/FIAliasAliasTag/fields3.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/fields3.c >& TestResults/FIAliasAliasTag/fields3.c.out
echo "Generating TestResults/FIAliasAliasTag/fields.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/fields.c >& TestResults/FIAliasAliasTag/fields.c.out
echo "Generating TestResults/FIAliasAliasTag/funCall.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/funCall.c >& TestResults/FIAliasAliasTag/funCall.c.out
echo "Generating TestResults/FIAliasAliasTag/func_call.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/func_call.c >& TestResults/FIAliasAliasTag/func_call.c.out
echo "Generating TestResults/FIAliasAliasTag/func-not-def.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/func-not-def.c >& TestResults/FIAliasAliasTag/func-not-def.c.out
echo "Generating TestResults/FIAliasAliasTag/functionPtr2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/functionPtr2.c >& TestResults/FIAliasAliasTag/functionPtr2.c.out
echo "Generating TestResults/FIAliasAliasTag/functionPtr.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/functionPtr.c >& TestResults/FIAliasAliasTag/functionPtr.c.out
echo "Generating TestResults/FIAliasAliasTag/invLoc.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/invLoc.c >& TestResults/FIAliasAliasTag/invLoc.c.out
echo "Generating TestResults/FIAliasAliasTag/LiangEtAl00.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/LiangEtAl00.c >& TestResults/FIAliasAliasTag/LiangEtAl00.c.out
echo "Generating TestResults/FIAliasAliasTag/LiangEtAl99.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/LiangEtAl99.c >& TestResults/FIAliasAliasTag/LiangEtAl99.c.out
echo "Generating TestResults/FIAliasAliasTag/LiangEtAlICSM99Fig2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/LiangEtAlICSM99Fig2.c >& TestResults/FIAliasAliasTag/LiangEtAlICSM99Fig2.c.out
echo "Generating TestResults/FIAliasAliasTag/LiangEtAlICSM99Fig5.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/LiangEtAlICSM99Fig5.c >& TestResults/FIAliasAliasTag/LiangEtAlICSM99Fig5.c.out
echo "Generating TestResults/FIAliasAliasTag/localNonLocal.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/localNonLocal.c >& TestResults/FIAliasAliasTag/localNonLocal.c.out
echo "Generating TestResults/FIAliasAliasTag/notConstQualified.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/notConstQualified.c >& TestResults/FIAliasAliasTag/notConstQualified.c.out
echo "Generating TestResults/FIAliasAliasTag/OAWikiEx.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/OAWikiEx.c >& TestResults/FIAliasAliasTag/OAWikiEx.c.out
echo "Generating TestResults/FIAliasAliasTag/passArrayPtr.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passArrayPtr.c >& TestResults/FIAliasAliasTag/passArrayPtr.c.out
echo "Generating TestResults/FIAliasAliasTag/passIntPtrArrayRef2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef2.c >& TestResults/FIAliasAliasTag/passIntPtrArrayRef2.c.out
echo "Generating TestResults/FIAliasAliasTag/passIntPtrArrayRef3.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef3.c >& TestResults/FIAliasAliasTag/passIntPtrArrayRef3.c.out
echo "Generating TestResults/FIAliasAliasTag/passIntPtrArrayRef.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef.c >& TestResults/FIAliasAliasTag/passIntPtrArrayRef.c.out
echo "Generating TestResults/FIAliasAliasTag/passIntPtr.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtr.c >& TestResults/FIAliasAliasTag/passIntPtr.c.out
echo "Generating TestResults/FIAliasAliasTag/ptr-arith.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/ptr-arith.c >& TestResults/FIAliasAliasTag/ptr-arith.c.out
echo "Generating TestResults/FIAliasAliasTag/retPtr1.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/retPtr1.c >& TestResults/FIAliasAliasTag/retPtr1.c.out
echo "Generating TestResults/FIAliasAliasTag/retPtr2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/retPtr2.c >& TestResults/FIAliasAliasTag/retPtr2.c.out
echo "Generating TestResults/FIAliasAliasTag/retPtr3.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/retPtr3.c >& TestResults/FIAliasAliasTag/retPtr3.c.out
echo "Generating TestResults/FIAliasAliasTag/retPtr4.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/retPtr4.c >& TestResults/FIAliasAliasTag/retPtr4.c.out
echo "Generating TestResults/FIAliasAliasTag/retPtr5.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/retPtr5.c >& TestResults/FIAliasAliasTag/retPtr5.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig11.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig11.c >& TestResults/FIAliasAliasTag/RyderEtAlFig11.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig14.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig14.c >& TestResults/FIAliasAliasTag/RyderEtAlFig14.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig15.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig15.c >& TestResults/FIAliasAliasTag/RyderEtAlFig15.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig1a.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig1a.c >& TestResults/FIAliasAliasTag/RyderEtAlFig1a.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig1b.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig1b.c >& TestResults/FIAliasAliasTag/RyderEtAlFig1b.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig1c.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig1c.c >& TestResults/FIAliasAliasTag/RyderEtAlFig1c.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig2.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig2.c >& TestResults/FIAliasAliasTag/RyderEtAlFig2.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig3.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig3.c >& TestResults/FIAliasAliasTag/RyderEtAlFig3.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig7.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig7.c >& TestResults/FIAliasAliasTag/RyderEtAlFig7.c.out
echo "Generating TestResults/FIAliasAliasTag/RyderEtAlFig9.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/RyderEtAlFig9.c >& TestResults/FIAliasAliasTag/RyderEtAlFig9.c.out
echo "Generating TestResults/FIAliasAliasTag/swap.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/swap.c >& TestResults/FIAliasAliasTag/swap.c.out
echo "Generating TestResults/FIAliasAliasTag/switchWithFuncCall.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/switchWithFuncCall.c >& TestResults/FIAliasAliasTag/switchWithFuncCall.c.out
echo "Generating TestResults/FIAliasAliasTag/t1.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/t1.c >& TestResults/FIAliasAliasTag/t1.c.out
echo "Generating TestResults/FIAliasAliasTag/ternop.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/ternop.c >& TestResults/FIAliasAliasTag/ternop.c.out
echo "Generating TestResults/FIAliasAliasTag/utke.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/utke.c >& TestResults/FIAliasAliasTag/utke.c.out
echo "Generating TestResults/FIAliasAliasTag/YongEtAlPLDI99.c.out"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/YongEtAlPLDI99.c >& TestResults/FIAliasAliasTag/YongEtAlPLDI99.c.out
