echo "Generating TestResults/ICFGReachConsts/constprop_if1a.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1a.c >& TestResults/ICFGReachConsts/constprop_if1a.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_if1b.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1b.c >& TestResults/ICFGReachConsts/constprop_if1b.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_if1c.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1c.c >& TestResults/ICFGReachConsts/constprop_if1c.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_loop1.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_loop1.c >& TestResults/ICFGReachConsts/constprop_loop1.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_loop2.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_loop2.c >& TestResults/ICFGReachConsts/constprop_loop2.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_proc1.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_proc1.c >& TestResults/ICFGReachConsts/constprop_proc1.c.out
echo "Generating TestResults/ICFGReachConsts/constprop_proc2.c.out"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_proc2.c >& TestResults/ICFGReachConsts/constprop_proc2.c.out
