echo "Generating TestResults/UDDUChainsTests/reachdef_if1.c.out"
./OATest -edg:w --oa-UDDUChains -c TestCases/UDDUChainsTests/reachdef_if1.c >& TestResults/UDDUChainsTests/reachdef_if1.c.out
echo "Generating TestResults/UDDUChainsTests/reachdef_if2.c.out"
./OATest -edg:w --oa-UDDUChains -c TestCases/UDDUChainsTests/reachdef_if2.c >& TestResults/UDDUChainsTests/reachdef_if2.c.out
echo "Generating TestResults/UDDUChainsTests/reachdef_loopif1.c.out"
./OATest -edg:w --oa-UDDUChains -c TestCases/UDDUChainsTests/reachdef_loopif1.c >& TestResults/UDDUChainsTests/reachdef_loopif1.c.out
