echo "Testing TestCases/AliasTests/alias1.c, TestResults/FIAliasAliasTag/alias1.c.out AIS (2/13/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias1.c >& t
diff t TestResults/FIAliasAliasTag/alias1.c.out

echo "Testing TestCases/AliasTests/alias2.c, TestResults/FIAliasAliasTag/alias2.c.out AIS (2/13/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias2.c >& t
diff t TestResults/FIAliasAliasTag/alias2.c.out

echo "Testing TestCases/AliasTests/alias3.c, TestResults/FIAliasAliasTag/alias3.c.out AIS (2/13/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias3.c >& t
diff t TestResults/FIAliasAliasTag/alias3.c.out

echo "Testing TestCases/AliasTests/alias4b.c, TestResults/FIAliasAliasTag/alias4b.c.out AIS (2/13/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias4b.c >& t
diff t TestResults/FIAliasAliasTag/alias4b.c.out

echo "Testing TestCases/AliasTests/alias4.c, TestResults/FIAliasAliasTag/alias4.c.out AIS (2/13/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/alias4.c >& t
diff t TestResults/FIAliasAliasTag/alias4.c.out

echo "Testing TestCases/AliasTests/comma.c, TestResults/FIAliasAliasTag/comma.c.out MMS (2/18/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/comma.c >& t
diff t TestResults/FIAliasAliasTag/comma.c.out

echo "Testing TestCases/AliasTests/constQualified.c, TestResults/FIAliasAliasTag/constQualified.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/constQualified.c >& t
diff t TestResults/FIAliasAliasTag/constQualified.c.out

echo "Testing TestCases/AliasTests/fields2.c, TestResults/FIAliasAliasTag/fields2.c.out MMS (2/18/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/fields2.c >& t
diff t TestResults/FIAliasAliasTag/fields2.c.out

echo "Testing TestCases/AliasTests/fields3.c, TestResults/FIAliasAliasTag/fields3.c.out MMS (2/18/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/fields3.c >& t
diff t TestResults/FIAliasAliasTag/fields3.c.out

echo "Testing TestCases/AliasTests/funCall.c, TestResults/FIAliasAliasTag/funCall.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/funCall.c >& t
diff t TestResults/FIAliasAliasTag/funCall.c.out

echo "Testing TestCases/AliasTests/functionPtr2.c, TestResults/FIAliasAliasTag/functionPtr2.c.out MMS (2/18/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/functionPtr2.c >& t
diff t TestResults/FIAliasAliasTag/functionPtr2.c.out

echo "Testing TestCases/AliasTests/functionPtr.c, TestResults/FIAliasAliasTag/functionPtr.c.out MMS (2/18/08)"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/functionPtr.c >& t
diff t TestResults/FIAliasAliasTag/functionPtr.c.out

echo "Testing TestCases/AliasTests/OAWikiEx.c, TestResults/FIAliasAliasTag/OAWikiEx.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/OAWikiEx.c >& t
diff t TestResults/FIAliasAliasTag/OAWikiEx.c.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef2.c, TestResults/FIAliasAliasTag/passIntPtrArrayRef2.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef2.c >& t
diff t TestResults/FIAliasAliasTag/passIntPtrArrayRef2.c.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef3.c, TestResults/FIAliasAliasTag/passIntPtrArrayRef3.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef3.c >& t
diff t TestResults/FIAliasAliasTag/passIntPtrArrayRef3.c.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef.c, TestResults/FIAliasAliasTag/passIntPtrArrayRef.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/passIntPtrArrayRef.c >& t
diff t TestResults/FIAliasAliasTag/passIntPtrArrayRef.c.out

echo "Testing TestCases/AliasTests/utke.c, TestResults/FIAliasAliasTag/utke.c.out ???"
./OATest --edg:no_warnings -w --oa-AliasTag -c TestCases/AliasTests/utke.c >& t
diff t TestResults/FIAliasAliasTag/utke.c.out

