echo "Testing TestCases/AliasTests/alias1.c, TestResults/AliasIRInterface/alias1.c.out checked by AIS 6/26/06"
./CtoOA TestCases/AliasTests/alias1.c > t
diff t TestResults/AliasIRInterface/alias1.c.out

echo "Testing TestCases/AliasTests/alias2.c, TestResults/AliasIRInterface/alias2.c.out checked by AIS 6/26/06"
./CtoOA TestCases/AliasTests/alias2.c > t
diff t TestResults/AliasIRInterface/alias2.c.out

echo "Testing TestCases/AliasTests/alias4.c, TestResults/AliasIRInterface/alias4.c.out checked by AIS 6/26/06"
./CtoOA TestCases/AliasTests/alias4.c > t
diff t TestResults/AliasIRInterface/alias4.c.out

echo "Testing TestCases/AliasTests/alias4b.c, TestResults/AliasIRInterface/alias4b.c.out checked by AIS 6/26/06"
./CtoOA TestCases/AliasTests/alias4b.c > t
diff t TestResults/AliasIRInterface/alias4b.c.out

echo "Testing TestCases/AliasTests/comma.c, TestResults/AliasIRInterface/comma.c.out checked by MMS 6/22/06"
./CtoOA TestCases/AliasTests/comma.c > t
diff t TestResults/AliasIRInterface/comma.c.out

