echo "Testing TestCases/ReachConstsTests/constprop_if1a.c, TestResults/ICFGReachConsts/constprop_if1a.c.out Checked by PLM 12/27/06"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1a.c >& t
diff t TestResults/ICFGReachConsts/constprop_if1a.c.out

echo "Testing TestCases/ReachConstsTests/constprop_if1b.c, TestResults/ICFGReachConsts/constprop_if1b.c.out Checked by PLM 12/27/06"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1b.c >& t
diff t TestResults/ICFGReachConsts/constprop_if1b.c.out

echo "Testing TestCases/ReachConstsTests/constprop_if1c.c, TestResults/ICFGReachConsts/constprop_if1c.c.out Checked by PLM 12/27/06"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_if1c.c >& t
diff t TestResults/ICFGReachConsts/constprop_if1c.c.out

echo "Testing TestCases/ReachConstsTests/constprop_proc2.c, TestResults/ICFGReachConsts/constprop_proc2.c.out Checked by PLM 12/27/06"
./OATest -edg:w --oa-ICFGReachConsts -c TestCases/ReachConstsTests/constprop_proc2.c >& t
diff t TestResults/ICFGReachConsts/constprop_proc2.c.out

