echo "Testing TestCases/AliasTests/alias1.c, TestResults/FIAliasAliasMap/alias1.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias1.c > t
diff t TestResults/FIAliasAliasMap/alias1.c.out

echo "Testing TestCases/AliasTests/alias2.c, TestResults/FIAliasAliasMap/alias2.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias2.c > t
diff t TestResults/FIAliasAliasMap/alias2.c.out

echo "Testing TestCases/AliasTests/alias3.c, TestResults/FIAliasAliasMap/alias3.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias3.c > t
diff t TestResults/FIAliasAliasMap/alias3.c.out

echo "Testing TestCases/AliasTests/alias4.c, TestResults/FIAliasAliasMap/alias4.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias4.c > t
diff t TestResults/FIAliasAliasMap/alias4.c.out

echo "Testing TestCases/AliasTests/alias4b.c, TestResults/FIAliasAliasMap/alias4b.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/alias4b.c > t
diff t TestResults/FIAliasAliasMap/alias4b.c.out

echo "Testing TestCases/AliasTests/comma.c, TestResults/FIAliasAliasMap/comma.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/comma.c > t
diff t TestResults/FIAliasAliasMap/comma.c.out

echo "Testing TestCases/AliasTests/constQualified.c, TestResults/FIAliasAliasMap/constQualified.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/constQualified.c > t
diff t TestResults/FIAliasAliasMap/constQualified.c.out

echo "Testing TestCases/AliasTests/utke.c, TestResults/FIAliasAliasMap/utke.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/utke.c > t
diff t TestResults/FIAliasAliasMap/utke.c.out

echo "Testing TestCases/AliasTests/OAWikiEx.c, TestResults/FIAliasAliasMap/OAWikiEx.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/OAWikiEx.c > t
diff t TestResults/FIAliasAliasMap/OAWikiEx.c.out

echo "Testing TestCases/AliasTests/funCall.c, TestResults/FIAliasAliasMap/funCall.c.out checked by AIS"
./OATest -edg:w --oa-FIAliasAliasMap -c TestCases/AliasTests/funCall.c > t
diff t TestResults/FIAliasAliasMap/funCall.c.out

