#! /bin/bash

# Example benchmark commands file:
#     Construct profiles for three different OA branches.
# By: Andy Stone (aistone@gmail.com)
# (C)opyright 2006, contributors of OpenAnalysis

ALGORITHM="--oa-FIAliasAliasMap"

# Say you want to profile three versions of OpenAnalysis.  These
# three versions exist in the branches: beforeChanges, afterChanges, and 
# afterSomeMoreChanges.  This script will use gprof to create 5 redundent
# profiles for each branch.  These profiles will be generated by using
# OATest to run the FIAliasAliasMap analysis algorithm against on a program
# who's files are listed in testProg.files.

#REDUNDENCIES=5

# Before running profiles we should make sure that the branches are properly
# compiled.  This script will compile each of the branches with the proper
# flags (-O3 -g -pg).  The branches are assumed to exist in subdirectories
# of $BRANCH_DIR.
compileOABranchForProfile "beforeChanges"
compileOABranchForProfile "afterChanges"
compileOABranchForProfile "afterSomeMoreChanges"

# For each of the three branches we want to test we need compile UseOA with
# the proper branch and then actually generate the profile.

useOABranch "/home/oadeveloper/mybranches/beforeChanges"
profile "testProg.files" "beforeChanges" 5

useOABranch "/home/oadeveloper/mybranches/afterChanges"
profile "testProg.files" "afterChanges" 5

useOABranch "/home/oadeveloper/mybranches/afterSomeMoreChanges"
profile "testProg.files" "afterSomeMoreChanges" 5

# ^^^^ note: the second parameter to the profile function doesn't necessarily
# have to be the name of the branch.  This parameter is used as a way to
# differentiate the profile generated with this call from the other ones in the
# script.  To get a clearer picture of why this might be useful notice it's
# usage in some of the other example scripts.

# this script will construct the following files for your viewing pleasure:
#    profile.beforeChanges.1
#    profile.beforeChanges.2
#    profile.beforeChanges.3
#    profile.beforeChanges.4
#    profile.beforeChanges.5
#    profile.afterChanges.1
#    profile.afterChanges.2
#    profile.afterChanges.3
#    profile.afterChanges.4
#    profile.afterChanges.5
#    profile.afterSomeMoreChanges.1
#    profile.afterSomeMoreChanges.2
#    profile.afterSomeMoreChanges.3
#    profile.afterSomeMoreChanges.4
#    profile.afterSomeMoreChanges.5
