echo "Generating TestResults/CFGtests/for.c.out"
./OATest -edg:w --oa-CFG -c TestCases/CFGtests/for.c >& TestResults/CFGtests/for.c.out
echo "Generating TestResults/CFGtests/while.c.out"
./OATest -edg:w --oa-CFG -c TestCases/CFGtests/while.c >& TestResults/CFGtests/while.c.out
echo "Generating TestResults/CFGtests/dowhile.c.out"
./OATest -edg:w --oa-CFG -c TestCases/CFGtests/dowhile.c >& TestResults/CFGtests/dowhile.c.out
echo "Generating TestResults/CFGtests/switch1.c.out"
./OATest -edg:w --oa-CFG -c TestCases/CFGtests/switch1.c >& TestResults/CFGtests/switch1.c.out
