echo "Testing TestCases/ExprTree/SimpleBalanced.c, TestResults/ExprTree/SimpleBalanced.c.out Checked by LMR 01/08/07"
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/SimpleBalanced.c >& t
diff t TestResults/ExprTree/SimpleBalanced.c.out

echo "Testing TestCases/ExprTree/SimpleCall2.c, TestResults/ExprTree/SimpleCall2.c.out Checked by LMR 01/08/07"
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/SimpleCall2.c >& t
diff t TestResults/ExprTree/SimpleCall2.c.out

echo "Testing TestCases/ExprTree/SimpleCall.c, TestResults/ExprTree/SimpleCall.c.out Checked by LMR 01/08/07"
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/SimpleCall.c >& t
diff t TestResults/ExprTree/SimpleCall.c.out

echo "Testing TestCases/ExprTree/SimpleSin.c, TestResults/ExprTree/SimpleSin.c.out Checked by LMR 01/08/07"
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/SimpleSin.c >& t
diff t TestResults/ExprTree/SimpleSin.c.out

echo "Testing TestCases/ExprTree/SimpleUnbalanced.c, TestResults/ExprTree/SimpleUnbalanced.c.out Checked by LMR 01/08/07"
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/SimpleUnbalanced.c >& t
diff t TestResults/ExprTree/SimpleUnbalanced.c.out

echo "Testing TestCases/ExprTree/integer_assignment.c, TestResults/ExprTree/integer_assignment.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/integer_assignment.c >& t
diff t TestResults/ExprTree/integer_assignment.c.out

echo "Testing TestCases/ExprTree/function.c, TestResults/ExprTree/function.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/function.c >& t
diff t TestResults/ExprTree/function.c.out

echo "Testing TestCases/ExprTree/function_pointer.c, TestResults/ExprTree/function_pointer.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/function_pointer.c >& t
diff t TestResults/ExprTree/function_pointer.c.out

echo "Testing TestCases/ExprTree/multiple_assignment.c, TestResults/ExprTree/multiple_assignment.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/multiple_assignment.c >& t
diff t TestResults/ExprTree/multiple_assignment.c.out

echo "Testing TestCases/ExprTree/multiple_operations.c, TestResults/ExprTree/multiple_operations.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/multiple_operations.c >& t
diff t TestResults/ExprTree/multiple_operations.c.out

echo "Testing TestCases/ExprTree/combine.c, TestResults/ExprTree/combine.c.out "
./OATest -edg:w --oa-ExprTree -c TestCases/ExprTree/combine.c >& t
diff t TestResults/ExprTree/combine.c.out

