echo "Generating TestResults/AliasIRInterface/addressOf.c.out"
./CtoOA TestCases/AliasTests/addressOf.c >& TestResults/AliasIRInterface/addressOf.c.out
echo "Generating TestResults/AliasIRInterface/aggregateInit.c.out"
./CtoOA TestCases/AliasTests/aggregateInit.c >& TestResults/AliasIRInterface/aggregateInit.c.out
echo "Generating TestResults/AliasIRInterface/alias1.c.out"
./CtoOA TestCases/AliasTests/alias1.c >& TestResults/AliasIRInterface/alias1.c.out
echo "Generating TestResults/AliasIRInterface/alias2.c.out"
./CtoOA TestCases/AliasTests/alias2.c >& TestResults/AliasIRInterface/alias2.c.out
echo "Generating TestResults/AliasIRInterface/alias4.c.out"
./CtoOA TestCases/AliasTests/alias4.c >& TestResults/AliasIRInterface/alias4.c.out
echo "Generating TestResults/AliasIRInterface/alias4b.c.out"
./CtoOA TestCases/AliasTests/alias4b.c >& TestResults/AliasIRInterface/alias4b.c.out
echo "Generating TestResults/AliasIRInterface/assignOps.c.out"
./CtoOA TestCases/AliasTests/assignOps.c >& TestResults/AliasIRInterface/assignOps.c.out
echo "Generating TestResults/AliasIRInterface/assignReturn.c.out"
./CtoOA TestCases/AliasTests/assignReturn.c >& TestResults/AliasIRInterface/assignReturn.c.out
echo "Generating TestResults/AliasIRInterface/class.C.out"
./CtoOA TestCases/AliasTests/class.C >& TestResults/AliasIRInterface/class.C.out
echo "Generating TestResults/AliasIRInterface/comma.c.out"
./CtoOA TestCases/AliasTests/comma.c >& TestResults/AliasIRInterface/comma.c.out
echo "Generating TestResults/AliasIRInterface/fields.c.out"
./CtoOA TestCases/AliasTests/fields.c >& TestResults/AliasIRInterface/fields.c.out
echo "Generating TestResults/AliasIRInterface/func_call.c.out"
./CtoOA TestCases/AliasTests/func_call.c >& TestResults/AliasIRInterface/func_call.c.out
echo "Generating TestResults/AliasIRInterface/functionPtr.c.out"
./CtoOA TestCases/AliasTests/functionPtr.c >& TestResults/AliasIRInterface/functionPtr.c.out
echo "Generating TestResults/AliasIRInterface/functionPtr2.c.out"
./CtoOA TestCases/AliasTests/functionPtr2.c >& TestResults/AliasIRInterface/functionPtr2.c.out
echo "Generating TestResults/AliasIRInterface/invokeBaseCtor.C.out"
./CtoOA TestCases/AliasTests/invokeBaseCtor.C >& TestResults/AliasIRInterface/invokeBaseCtor.C.out
echo "Generating TestResults/AliasIRInterface/localNonLocal.c.out"
./CtoOA TestCases/AliasTests/localNonLocal.c >& TestResults/AliasIRInterface/localNonLocal.c.out
echo "Generating TestResults/AliasIRInterface/passArrayPtr.c.out"
./CtoOA TestCases/AliasTests/passArrayPtr.c >& TestResults/AliasIRInterface/passArrayPtr.c.out
echo "Generating TestResults/AliasIRInterface/parambinds-formals-intPtrs.C.out"
./CtoOA TestCases/AliasTests/parambinds-formals-intPtrs.C >& TestResults/AliasIRInterface/parambinds-formals-intPtrs.C.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef.c.out"
./CtoOA TestCases/AliasTests/passIntPtrArrayRef.c >& TestResults/AliasIRInterface/passIntPtrArrayRef.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef2.c.out"
./CtoOA TestCases/AliasTests/passIntPtrArrayRef2.c >& TestResults/AliasIRInterface/passIntPtrArrayRef2.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef3.c.out"
./CtoOA TestCases/AliasTests/passIntPtrArrayRef3.c >& TestResults/AliasIRInterface/passIntPtrArrayRef3.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtr.c.out"
./CtoOA TestCases/AliasTests/passIntPtr.c >& TestResults/AliasIRInterface/passIntPtr.c.out
echo "Generating TestResults/AliasIRInterface/refParam.C.out"
./CtoOA TestCases/AliasTests/refParam.C >& TestResults/AliasIRInterface/refParam.C.out
echo "Generating TestResults/AliasIRInterface/ref.C.out"
./CtoOA TestCases/AliasTests/ref.C >& TestResults/AliasIRInterface/ref.C.out
echo "Generating TestResults/AliasIRInterface/refClass.C.out"
./CtoOA TestCases/AliasTests/refClass.C >& TestResults/AliasIRInterface/refClass.C.out
echo "Generating TestResults/AliasIRInterface/refClass2.C.out"
./CtoOA TestCases/AliasTests/refClass2.C >& TestResults/AliasIRInterface/refClass2.C.out
echo "Generating TestResults/AliasIRInterface/retPtr1.c.out"
./CtoOA TestCases/AliasTests/retPtr1.c >& TestResults/AliasIRInterface/retPtr1.c.out
echo "Generating TestResults/AliasIRInterface/sizeOf.C.out"
./CtoOA TestCases/AliasTests/sizeOf.C >& TestResults/AliasIRInterface/sizeOf.C.out
echo "Generating TestResults/AliasIRInterface/swap.c.out"
./CtoOA TestCases/AliasTests/swap.c >& TestResults/AliasIRInterface/swap.c.out
echo "Generating TestResults/AliasIRInterface/ternop.c.out"
./CtoOA TestCases/AliasTests/ternop.c >& TestResults/AliasIRInterface/ternop.c.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForDotMethodInvoc.C.out"
./CtoOA TestCases/AliasTests/paramBindingsForDotMethodInvoc.C >& TestResults/AliasIRInterface/paramBindingsForDotMethodInvoc.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForArrowMethodInvoc.C.out"
./CtoOA TestCases/AliasTests/paramBindingsForArrowMethodInvoc.C >& TestResults/AliasIRInterface/paramBindingsForArrowMethodInvoc.C.out
