echo "Generating TestResults/AliasIRInterface/addressOf.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/addressOf.c >& TestResults/AliasIRInterface/addressOf.c.out
echo "Generating TestResults/AliasIRInterface/aggregateInit.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/aggregateInit.c >& TestResults/AliasIRInterface/aggregateInit.c.out
echo "Generating TestResults/AliasIRInterface/alias1.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/alias1.c >& TestResults/AliasIRInterface/alias1.c.out
echo "Generating TestResults/AliasIRInterface/alias2.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/alias2.c >& TestResults/AliasIRInterface/alias2.c.out
echo "Generating TestResults/AliasIRInterface/alias4.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/alias4.c >& TestResults/AliasIRInterface/alias4.c.out
echo "Generating TestResults/AliasIRInterface/alias4b.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/alias4b.c >& TestResults/AliasIRInterface/alias4b.c.out
echo "Generating TestResults/AliasIRInterface/assignOps.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignOps.c >& TestResults/AliasIRInterface/assignOps.c.out
echo "Generating TestResults/AliasIRInterface/assignReturn.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignReturn.c >& TestResults/AliasIRInterface/assignReturn.c.out
echo "Generating TestResults/AliasIRInterface/class.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/class.C >& TestResults/AliasIRInterface/class.C.out
echo "Generating TestResults/AliasIRInterface/comma.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/comma.c >& TestResults/AliasIRInterface/comma.c.out
echo "Generating TestResults/AliasIRInterface/fields.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/fields.c >& TestResults/AliasIRInterface/fields.c.out
echo "Generating TestResults/AliasIRInterface/constQualified.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/constQualified.c >& TestResults/AliasIRInterface/constQualified.c.out
echo "Generating TestResults/AliasIRInterface/func_call.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/func_call.c >& TestResults/AliasIRInterface/func_call.c.out
echo "Generating TestResults/AliasIRInterface/functionPtr.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/functionPtr.c >& TestResults/AliasIRInterface/functionPtr.c.out
echo "Generating TestResults/AliasIRInterface/functionPtr2.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/functionPtr2.c >& TestResults/AliasIRInterface/functionPtr2.c.out
echo "Generating TestResults/AliasIRInterface/implicitMemberVarAccess.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitMemberVarAccess.C >& TestResults/AliasIRInterface/implicitMemberVarAccess.C.out
echo "Generating TestResults/AliasIRInterface/implicitMemberVarAccessInCtorList.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitMemberVarAccessInCtorList.C >& TestResults/AliasIRInterface/implicitMemberVarAccessInCtorList.C.out
echo "Generating TestResults/AliasIRInterface/implicitMemberVarObjDefnInCtorList.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitMemberVarObjDefnInCtorList.C >& TestResults/AliasIRInterface/implicitMemberVarObjDefnInCtorList.C.out
echo "Generating TestResults/AliasIRInterface/implicitMemberVarRefDefnInCtorList.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitMemberVarRefDefnInCtorList.C >& TestResults/AliasIRInterface/implicitMemberVarRefDefnInCtorList.C.out
echo "Generating TestResults/AliasIRInterface/implicitReceiverCtorInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitReceiverCtorInvoc.C >& TestResults/AliasIRInterface/implicitReceiverCtorInvoc.C.out
echo "Generating TestResults/AliasIRInterface/implicitReceiverDestructorInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitReceiverDestructorInvoc.C >& TestResults/AliasIRInterface/implicitReceiverDestructorInvoc.C.out
echo "Generating TestResults/AliasIRInterface/implicitReceiverMethodInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/implicitReceiverMethodInvoc.C >& TestResults/AliasIRInterface/implicitReceiverMethodInvoc.C.out
echo "Generating TestResults/AliasIRInterface/invokeBaseCtor.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/invokeBaseCtor.C >& TestResults/AliasIRInterface/invokeBaseCtor.C.out
echo "Generating TestResults/AliasIRInterface/invokeBaseCtorInCtorList.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/invokeBaseCtorInCtorList.C >& TestResults/AliasIRInterface/invokeBaseCtorInCtorList.C.out
echo "Generating TestResults/AliasIRInterface/passArrayPtr.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/passArrayPtr.c >& TestResults/AliasIRInterface/passArrayPtr.c.out
echo "Generating TestResults/AliasIRInterface/parambinds-formals-intPtrs.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/parambinds-formals-intPtrs.C >& TestResults/AliasIRInterface/parambinds-formals-intPtrs.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForArrowMethodInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForArrowMethodInvoc.C >& TestResults/AliasIRInterface/paramBindingsForArrowMethodInvoc.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForDotMethodInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForDotMethodInvoc.C >& TestResults/AliasIRInterface/paramBindingsForDotMethodInvoc.C.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/passIntPtrArrayRef.c >& TestResults/AliasIRInterface/passIntPtrArrayRef.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef2.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/passIntPtrArrayRef2.c >& TestResults/AliasIRInterface/passIntPtrArrayRef2.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtrArrayRef3.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/passIntPtrArrayRef3.c >& TestResults/AliasIRInterface/passIntPtrArrayRef3.c.out
echo "Generating TestResults/AliasIRInterface/passIntPtr.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/passIntPtr.c >& TestResults/AliasIRInterface/passIntPtr.c.out
echo "Generating TestResults/AliasIRInterface/refParam.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/refParam.C >& TestResults/AliasIRInterface/refParam.C.out
echo "Generating TestResults/AliasIRInterface/ref.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/ref.C >& TestResults/AliasIRInterface/ref.C.out
echo "Generating TestResults/AliasIRInterface/refClass.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/refClass.C >& TestResults/AliasIRInterface/refClass.C.out
echo "Generating TestResults/AliasIRInterface/refClass2.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/refClass2.C >& TestResults/AliasIRInterface/refClass2.C.out
echo "Generating TestResults/AliasIRInterface/retPtr1.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/retPtr1.c >& TestResults/AliasIRInterface/retPtr1.c.out
echo "Generating TestResults/AliasIRInterface/sizeOf.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/sizeOf.C >& TestResults/AliasIRInterface/sizeOf.C.out
echo "Generating TestResults/AliasIRInterface/swap.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/swap.c >& TestResults/AliasIRInterface/swap.c.out
echo "Generating TestResults/AliasIRInterface/ternop.c.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/ternop.c >& TestResults/AliasIRInterface/ternop.c.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForStaticMethodInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForStaticMethodInvoc.C >& TestResults/AliasIRInterface/paramBindingsForStaticMethodInvoc.C.out
echo "Generating TestResults/AliasIRInterface/staticMemberVarAccess.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/staticMemberVarAccess.C >& TestResults/AliasIRInterface/staticMemberVarAccess.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForStackCtorInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForStackCtorInvoc.C >& TestResults/AliasIRInterface/paramBindingsForStackCtorInvoc.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForDynamicCtorInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForDynamicCtorInvoc.C >& TestResults/AliasIRInterface/paramBindingsForDynamicCtorInvoc.C.out
echo "Generating TestResults/AliasIRInterface/paramBindingsForDestructorInvoc.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/paramBindingsForDestructorInvoc.C >& TestResults/AliasIRInterface/paramBindingsForDestructorInvoc.C.out
echo "Generating TestResults/AliasIRInterface/stackInitOfClassWithVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/stackInitOfClassWithVirtualMethods.C >& TestResults/AliasIRInterface/stackInitOfClassWithVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/dynamicInitOfClassWithVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/dynamicInitOfClassWithVirtualMethods.C >& TestResults/AliasIRInterface/dynamicInitOfClassWithVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/virtualDotMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualDotMethodInvocation.C >& TestResults/AliasIRInterface/virtualDotMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/virtualArrowMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualArrowMethodInvocation.C >& TestResults/AliasIRInterface/virtualArrowMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/assignOfObjectPtrWithVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignOfObjectPtrWithVirtualMethods.C >& TestResults/AliasIRInterface/assignOfObjectPtrWithVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/stackInitOfClassWhoseBaseClassHasVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/stackInitOfClassWhoseBaseClassHasVirtualMethods.C >& TestResults/AliasIRInterface/stackInitOfClassWhoseBaseClassHasVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/dynamicInitOfClassWhoseBaseClassHasVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/dynamicInitOfClassWhoseBaseClassHasVirtualMethods.C >& TestResults/AliasIRInterface/dynamicInitOfClassWhoseBaseClassHasVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/virtualDotBaseMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualDotBaseMethodInvocation.C >& TestResults/AliasIRInterface/virtualDotBaseMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/virtualDotRefBaseMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualDotRefBaseMethodInvocation.C >& TestResults/AliasIRInterface/virtualDotRefBaseMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/virtualArrowBaseMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualArrowBaseMethodInvocation.C >& TestResults/AliasIRInterface/virtualArrowBaseMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/assignOfObjPtrWhoseBaseClassHasVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignOfObjPtrWhoseBaseClassHasVirtualMethods.C >& TestResults/AliasIRInterface/assignOfObjPtrWhoseBaseClassHasVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/stackInitOfClassThatOverloadsBaseClassVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/stackInitOfClassThatOverloadsBaseClassVirtualMethods.C >& TestResults/AliasIRInterface/stackInitOfClassThatOverloadsBaseClassVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/stackInitOfClassThatOverloadsBaseClassPureVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/stackInitOfClassThatOverloadsBaseClassPureVirtualMethods.C >& TestResults/AliasIRInterface/stackInitOfClassThatOverloadsBaseClassPureVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/dynamicInitOfClassThatOverloadsBaseClassVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/dynamicInitOfClassThatOverloadsBaseClassVirtualMethods.C >& TestResults/AliasIRInterface/dynamicInitOfClassThatOverloadsBaseClassVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/dynamicInitOfClassThatOverloadsBaseClassPureVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/dynamicInitOfClassThatOverloadsBaseClassPureVirtualMethods.C >& TestResults/AliasIRInterface/dynamicInitOfClassThatOverloadsBaseClassPureVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/virtualDotOverloadedBaseMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualDotOverloadedBaseMethodInvocation.C >& TestResults/AliasIRInterface/virtualDotOverloadedBaseMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/virtualArrowOverloadedBaseMethodInvocation.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/virtualArrowOverloadedBaseMethodInvocation.C >& TestResults/AliasIRInterface/virtualArrowOverloadedBaseMethodInvocation.C.out
echo "Generating TestResults/AliasIRInterface/assignOfObjPtrThatOverloadsBaseClassVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignOfObjPtrThatOverloadsBaseClassVirtualMethods.C >& TestResults/AliasIRInterface/assignOfObjPtrThatOverloadsBaseClassVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/assignOfObjPtrThatOverloadsBaseClassPureVirtualMethods.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/assignOfObjPtrThatOverloadsBaseClassPureVirtualMethods.C >& TestResults/AliasIRInterface/assignOfObjPtrThatOverloadsBaseClassPureVirtualMethods.C.out
echo "Generating TestResults/AliasIRInterface/ctorReferenceInit.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/ctorReferenceInit.C >& TestResults/AliasIRInterface/ctorReferenceInit.C.out
echo "Generating TestResults/AliasIRInterface/refPtrFormal.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/refPtrFormal.C >& TestResults/AliasIRInterface/refPtrFormal.C.out
echo "Generating TestResults/AliasIRInterface/referenceMemVarAccesses.C.out"
./CtoOA --edg:no_warnings -w TestCases/AliasTests/referenceMemVarAccesses.C >& TestResults/AliasIRInterface/referenceMemVarAccesses.C.out
