echo "Testing TestCases/AliasTests/addressOf.c, TestResults/AliasIRInterfacePerMethodModel/addressOf.c.out checked by MMS 8/20/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/addressOf.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/addressOf.c.out

echo "Testing TestCases/AliasTests/aggregateInit.c, TestResults/AliasIRInterfacePerMethodModel/aggregateInit.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/aggregateInit.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/aggregateInit.c.out

echo "Testing TestCases/AliasTests/alias1.c, TestResults/AliasIRInterfacePerMethodModel/alias1.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/alias1.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/alias1.c.out

echo "Testing TestCases/AliasTests/alias2.c, TestResults/AliasIRInterfacePerMethodModel/alias2.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/alias2.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/alias2.c.out

echo "Testing TestCases/AliasTests/alias4.c, TestResults/AliasIRInterfacePerMethodModel/alias4.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/alias4.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/alias4.c.out

echo "Testing TestCases/AliasTests/alias4b.c, TestResults/AliasIRInterfacePerMethodModel/alias4b.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/alias4b.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/alias4b.c.out

echo "Testing TestCases/AliasTests/assignOps.c, TestResults/AliasIRInterfacePerMethodModel/assignOps.c.out checked by MMS 8/13/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/assignOps.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/assignOps.c.out

echo "Testing TestCases/AliasTests/assignReturn.c, TestResults/AliasIRInterfacePerMethodModel/assignReturn.c.out checked by MMS 8/20/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/assignReturn.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/assignReturn.c.out

echo "Testing TestCases/AliasTests/class.C, TestResults/AliasIRInterfacePerMethodModel/class.C.out missing LOC for sInt MMS 8/23/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/class.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/class.C.out

echo "Testing TestCases/AliasTests/comma.c, TestResults/AliasIRInterfacePerMethodModel/comma.c.out UnnamedRefs right? MMS 8/23/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/comma.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/comma.c.out

echo "Testing TestCases/AliasTests/fields.c, TestResults/AliasIRInterfacePerMethodModel/fields.c.out checked by MMS 8/20/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/fields.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/fields.c.out

echo "Testing TestCases/AliasTests/func_call.c, TestResults/AliasIRInterfacePerMethodModel/func_call.c.out p=fp2() has two MemRefHandles that are the same? aborting MMS 8/1/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/func_call.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/func_call.c.out

echo "Testing TestCases/AliasTests/functionPtr.c, TestResults/AliasIRInterfacePerMethodModel/functionPtr.c.out checked by MMS 8/22/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/functionPtr.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/functionPtr.c.out

echo "Testing TestCases/AliasTests/functionPtr2.c, TestResults/AliasIRInterfacePerMethodModel/functionPtr2.c.out checked by MMS 8/22/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/functionPtr2.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/functionPtr2.c.out

echo "Testing TestCases/AliasTests/invokeBaseCtor.C, TestResults/AliasIRInterfacePerMethodModel/invokeBaseCtor.C.out checked by BSW 6/26/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/invokeBaseCtor.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/invokeBaseCtor.C.out

echo "Testing TestCases/AliasTests/localNonLocal.c, TestResults/AliasIRInterfacePerMethodModel/localNonLocal.c.out checked by BSW 6/28/06 (rechecked by MMS 8/21/06)"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/localNonLocal.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/localNonLocal.c.out

echo "Testing TestCases/AliasTests/passArrayPtr.c, TestResults/AliasIRInterfacePerMethodModel/passArrayPtr.c.out checked by MMS 7/27/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/passArrayPtr.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/passArrayPtr.c.out

echo "Testing TestCases/AliasTests/parambinds-formals-intPtrs.C, TestResults/AliasIRInterfacePerMethodModel/parambinds-formals-intPtrs.C.out should ap be formal param? MMS 8/7/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/parambinds-formals-intPtrs.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/parambinds-formals-intPtrs.C.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef.c, TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef.c.out checked by MMS 7/24/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/passIntPtrArrayRef.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef.c.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef2.c, TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef2.c.out checked by MMS 7/24/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/passIntPtrArrayRef2.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef2.c.out

echo "Testing TestCases/AliasTests/passIntPtrArrayRef3.c, TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef3.c.out checked by MMS 7/24/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/passIntPtrArrayRef3.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/passIntPtrArrayRef3.c.out

echo "Testing TestCases/AliasTests/passIntPtr.c, TestResults/AliasIRInterfacePerMethodModel/passIntPtr.c.out checked by MMS 8/21/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/passIntPtr.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/passIntPtr.c.out

echo "Testing TestCases/AliasTests/refParam.C, TestResults/AliasIRInterfacePerMethodModel/refParam.C.out checked by MMS 8/24/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/refParam.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/refParam.C.out

echo "Testing TestCases/AliasTests/ref.C, TestResults/AliasIRInterfacePerMethodModel/ref.C.out checked by MMS 8/21/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/ref.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/ref.C.out

echo "Testing TestCases/AliasTests/refClass.C, TestResults/AliasIRInterfacePerMethodModel/refClass.C.out ctor inits should be defining namedrefs not derefs MMS 8/1/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/refClass.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/refClass.C.out

echo "Testing TestCases/AliasTests/refClass2.C, TestResults/AliasIRInterfacePerMethodModel/refClass2.C.out ctor inits should be defining namedrefs not derefs MMS 8/1/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/refClass2.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/refClass2.C.out

echo "Testing TestCases/AliasTests/retPtr1.c, TestResults/AliasIRInterfacePerMethodModel/retPtr1.c.out checked by MMS 8/24/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/retPtr1.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/retPtr1.c.out

echo "Testing TestCases/AliasTests/sizeOf.C, TestResults/AliasIRInterfacePerMethodModel/sizeOf.C.out checked by MMS 8/24/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/sizeOf.C >& t
diff t TestResults/AliasIRInterfacePerMethodModel/sizeOf.C.out

echo "Testing TestCases/AliasTests/swap.c, TestResults/AliasIRInterfacePerMethodModel/swap.c.out i++ should be USEDEF otherwise fine MMS 7/23/06 XXX"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/swap.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/swap.c.out

echo "Testing TestCases/AliasTests/ternop.c, TestResults/AliasIRInterfacePerMethodModel/ternop.c.out checked by MMS 8/24/06"
./CtoOA --usePerMethodVirtualModel TestCases/AliasTests/ternop.c >& t
diff t TestResults/AliasIRInterfacePerMethodModel/ternop.c.out

